### ISSUE TITLE
Not removing birthday's

### ISSUE THREAD

**Issue by RiZ266** [scottbucher/BirthdayBot#201] opened 2022-03-17 14:17 UTC
Hi there I have an issue with the birthday not not removing birthday roles after 24hrs. It's been 2 days and a user still hasn't had the role removed by the bot. Is there a command for the bot we can use to remove the role ourselves instead if having the server owner do it?

**Comment by scottbucher** [comment] 2022-03-17 20:41
Duplicate of #148

**Closed by scottbucher** 2022-03-17 20:41 UTC
